movieapp/urls.py
from django.urls import path,include
from . import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('addmovie',views.adddetails,name='addmovie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movielist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img = models.ImageField(upload_to='pics')

    def __str__(self):
        return self.name

movieapp/forms.py
from django import forms
from .models import movie

class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import movie
from .forms import movieform
# Create your views here.
def index(request):
    object=movie.objects.all()
    return render(request,'index.html',{'movie':object})
def detail(request,movie_id):
    mov=movie.objects.get(id=movie_id)
    return render(request,'details.html',{'mov':mov})
def adddetails(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img=request.FILES['img']
        mov=movie(name=name,desc=desc,year=year,img=img)
        mov.save()
    return render(request,'adddetails.html')
def update(request,id):
    mov=movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=mov)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'mov':mov})
def delete(request,id):
    if request.method=='POST':
        mov=movie.objects.get(id=id)
        mov.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/adddetails.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name"><br>
        <input type="text" name="desc" placeholder="Enter the movie description"><br>
        <input type="number" name="year" placeholder="Enter the movie year"><br>
      <input type="file" name="img"><br>
    <input type="submit">
</form>

templates/base.html
<!--{% load static %}-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MOVIES</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU" crossorigin="anonymous">

</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'movieapp:addmovie' %}">Add Movie</a>
        </li>
        {% comment %} <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> {% endcomment %}
      </ul>
    </div>
  </div>
</nav>
    
  

{% block content %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="post" >
{% csrf_token %}
Are u sure u whant to delete
<input type="submit">

</form>

templates/details.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
<h3>{{mov.name}}</h3><br>
<img src="{{mov.img.url}}" align="center" height="250px" width="190px"><br>
            <h5>{{mov.desc}}</h5><br>
            <h5> Release year :{{mov.year}}</h5><br>
<a class="btn btn-primary" href="{% url 'movieapp:update' mov.id %}">Update</a>
<a class="btn btn-outline-danger" href="{% url 'movieapp:delete' mov.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

templates/edit.html
<form method="post" enctype="multipart/form-data">
{% csrf_token %}
 {{form.as_p}}
 <input type="submit">
</form>

templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}>  
<div class="container">
    <div class="row">
{% for i in movie %}
        <div class="col-md-3">
         <div class="card h-100" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-outline-success">Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>


<!--<h4> description: {{i.desc}}</h4>-->
<!--<h5> year:{{i.year}}</h5>-->


{% endblock %}